name: copy markdown files
on:
  push:
    branches: [ main ]
    paths: 'dir1/*/*.md'
  workflow_dispatch:
jobs:
  copy-test:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/62432172/github-action-to-copy-and-a-rename-a-file
    steps:
    - uses: actions/checkout@v4
    - name: Install rsync
      run: sudo apt-get install -y rsync
    - name: Make the script files executable
      run: chmod +x scripts/copytest.sh
    - name: Copy the markdown files
      working-directory: ./scripts
      run: |
        ./copytest.sh
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
